INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES(1, 'Solteiro'); 
INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES(2, 'Casado'); 
INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES(3, 'Separado'); 
INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES(4, 'Divorciado'); 
INSERT INTO TB_ESTADO_CIVIL (ID, DESCRICAO) VALUES(5, 'Viúvo'); 