CREATE TABLE TB_ESTADO_CIVIL (
    ID INTEGER NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL 
);

CREATE TABLE TB_PESSOA (
    ID IDENTITY NOT NULL PRIMARY KEY, 
    NOME VARCHAR(255) NOT NULL, 
    ID_ESTADO_CIVIL INTEGER NOT NULL, 
    DATA_NASCIMENTO DATE NOT NULL, 
    NOME_PARCEIRO VARCHAR(255) NULL,
    DATA_NASCIMENTO_PARCEIRO DATE NULL,
    FOREIGN KEY(ID_ESTADO_CIVIL) REFERENCES TB_ESTADO_CIVIL(ID)
);
